name: Vision Strategic Planning
favicon: null
layout_spectrum: 0.8057174587156624
typography_spectrum: 0.9764528314117342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f5da'
    - '#000000'
    - '#ffff00'
    - '#808080'
    - '#80ff80'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.38226705719716847
  rhythmicContrast: 0.09724502940662205
purpose: []
